{"name": "login with invalid credential -- @1.1 ", "status": "failed", "statusDetails": {"message": "AssertionError:   Login failed\n", "trace": "  File \"C:\\Users\\LENOVO\\AppData\\Roaming\\Python\\Python312\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\LENOVO\\AppData\\Roaming\\Python\\Python312\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\codeLogin.py\", line 39, in putdata\n    context.login_obj.valiData(username,password)                         #function call from login_webPage.py\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\LENOVO\\VScodeProjects\\autoTest\\features\\web_pages\\login_webPage.py\", line 34, in valiData\n    assert url_2==url_login,\"  Login failed\"\n           ^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Given user already on login page", "status": "passed", "start": 1730106547091, "stop": 1730106547106}, {"name": "When we fill invalid testuser and testpass", "status": "failed", "statusDetails": {"message": "AssertionError:   Login failed\n", "trace": "  File \"C:\\Users\\LENOVO\\AppData\\Roaming\\Python\\Python312\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\LENOVO\\AppData\\Roaming\\Python\\Python312\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\codeLogin.py\", line 39, in putdata\n    context.login_obj.valiData(username,password)                         #function call from login_webPage.py\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\LENOVO\\VScodeProjects\\autoTest\\features\\web_pages\\login_webPage.py\", line 34, in valiData\n    assert url_2==url_login,\"  Login failed\"\n           ^^^^^^^^^^^^^^^^\n"}, "attachments": [{"name": "failed_ss", "source": "3baf377a-cf83-4375-9dc2-711a205704d2-attachment.attach", "type": "AttachmentType.PNG"}], "start": 1730106547106, "stop": 1730106547662}, {"name": "Then error message appear,process complete", "status": "skipped", "start": 1730106547677, "stop": 1730106547677}], "parameters": [{"name": "username", "value": "testuser"}, {"name": "password", "value": "testpass"}], "start": 1730106541105, "stop": 1730106547677, "uuid": "4528e94c-5e9d-42e7-a5e0-82cb5ffff0a2", "historyId": "9041fa8cde75cd765eff357da0736cae", "fullName": "Login panel of saucedemo verify credentials: login with invalid credential", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "logineg"}, {"name": "feature", "value": "Login panel of saucedemo verify credentials"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}