{"name": "login with invalid credential -- @1.2 ", "status": "failed", "statusDetails": {"message": "AssertionError:   Login failed\n", "trace": "  File \"C:\\Users\\LENOVO\\AppData\\Roaming\\Python\\Python312\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\LENOVO\\AppData\\Roaming\\Python\\Python312\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\codeLogin.py\", line 39, in putdata\n    context.login_obj.valiData(username,password)                         #function call from login_webPage.py\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\LENOVO\\VScodeProjects\\autoTest\\features\\web_pages\\login_webPage.py\", line 34, in valiData\n    assert url_2==url_login,\"  Login failed\"\n           ^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Given user already on login page", "status": "passed", "start": 1730106553653, "stop": 1730106553668}, {"name": "When we fill invalid #@%@$@$^ and ^$#^$Rpass456", "status": "failed", "statusDetails": {"message": "AssertionError:   Login failed\n", "trace": "  File \"C:\\Users\\LENOVO\\AppData\\Roaming\\Python\\Python312\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\LENOVO\\AppData\\Roaming\\Python\\Python312\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\codeLogin.py\", line 39, in putdata\n    context.login_obj.valiData(username,password)                         #function call from login_webPage.py\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\LENOVO\\VScodeProjects\\autoTest\\features\\web_pages\\login_webPage.py\", line 34, in valiData\n    assert url_2==url_login,\"  Login failed\"\n           ^^^^^^^^^^^^^^^^\n"}, "attachments": [{"name": "failed_ss", "source": "947b8800-093d-42ac-9c9b-fa42dddf4341-attachment.attach", "type": "AttachmentType.PNG"}], "start": 1730106553669, "stop": 1730106554167}, {"name": "Then error message appear,process complete", "status": "skipped", "start": 1730106554167, "stop": 1730106554167}], "parameters": [{"name": "username", "value": "#@%@$@$^"}, {"name": "password", "value": "^$#^$Rpass456"}], "start": 1730106547677, "stop": 1730106554167, "uuid": "4d719e6b-5ceb-449c-8550-19077d2a927e", "historyId": "12921a13ff5ccc8e80f510f5f2520144", "fullName": "Login panel of saucedemo verify credentials: login with invalid credential", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "logineg"}, {"name": "feature", "value": "Login panel of saucedemo verify credentials"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}